export const category_api_url = "https://157.230.240.97:9999/api/v1/categories";

export const product_list_url =
  "https://157.230.240.97:9999/api/v1/shop/products";

export const product_details_url = "https://157.230.240.97:9999/api/v1/product";

export const dummytext =
  "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi iste aliquam voluptatibus consequatur excepturi. Dolore accusamus quia tempora, repellat nisi odit mollitia dolor necessitatibus, reiciendis eveniet perspiciatis in harum. Sit quae laboriosam nulla reprehenderit labore facilis nostrum, debitis voluptatem perspiciatis dolorum minus voluptates accusamus corporis beatae quam a modi, laudantium assumenda cum, itaque error! Beatae maiores, alias quos ea qui earum odio delectus asperiores facilis rerum quasi itaque, cupiditate omnis nemo ullam ratione dicta animi suscipit quaerat vel! Excepturi in a ullam recusandae consectetur dolorum debitis nihil, facilis minima rem officiis natus atque? Recusandae fugit sit dolorem repudiandae cumque, commodi blanditiis porro assumenda quasi, harum aperiam eveniet itaque repellat ratione officiis repellendus dolores iure expedita unde maiores autem minus? Corporis placeat, quo asperiores consequatur vitae inventore libero facere animi qui, tenetur doloribus tempore! Nisi atque iusto autem incidunt a cum quia dolor numquam explicabo maxime consequatur vero, aliquam corrupti cumque. Maiores, labore, accusantium commodi dolores reiciendis in, sed tenetur ullam magni incidunt illo eos adipisci blanditiis delectus saepe hic beatae excepturi tempora. Dolores nisi iste molestiae repellendus natus doloremque distinctio quae eos aliquid sunt laboriosam iusto recusandae hic fuga magnam porro, tempore sequi assumenda? Recusandae, possimus quis? Voluptas laborum quo corporis illo architecto voluptatem et, deleniti ipsam. Provident corrupti laboriosam labore ipsa dolore ratione, fuga consequatur distinctio illo, tempora molestias soluta reprehenderit, natus fugit suscipit? Ad quos illo deleniti laboriosam expedita suscipit similique dolore temporibus vel! Ducimus deserunt, amet fugiat, dolorem quas omnis doloremque architecto aperiam dignissimos pariatur nemo itaque, suscipit voluptatibus unde perferendis qui. Sed veniam beatae inventore debitis, minus eos blanditiis, sunt nostrum reprehenderit rerum, libero cupiditate a numquam rem tempora at? Itaque odit ipsum hic eveniet quae consequatur, modi doloremque rem asperiores quos dolorum, id qui eaque. Sed ullam ducimus necessitatibus mollitia cum culpa facilis earum. Aperiam repudiandae, quasi quam eum dolores perferendis, vitae labore ratione incidunt quis ea. Blanditiis velit labore deserunt ipsa id unde fugiat aut voluptas distinctio rerum, quisquam dicta ratione ab error non debitis laborum nisi atque fugit eligendi sint doloribus minima et enim. Ex numquam magnam qui ducimus hic dolores ipsam ipsum est. Sed eveniet distinctio quisquam officia nam. Dolores consequatur est reprehenderit deleniti optio sed rerum libero, nemo nobis. Ex esse deserunt fuga ad odit ipsa tempore provident voluptatem iure rerum, ipsum exercitationem molestias porro eos quaerat dolor. Non placeat animi a officiis porro sint culpa assumenda facilis necessitatibus quidem? Dignissimos!";
